### ISSUE TITLE
Implementacja  podstawowego GUI

### ISSUE THREAD

**Issue by adamm123** [mateusz59861/PZ-gr.2#18]
Bez integracji z API(tylko warstwa graficzna)
- okienko
- zakładki
- listy zasobów
- placeholdery dla komponentów wykresów
- itd

**Comment by Udiknedormin** [comment]
Z wymienionych zrobione są wszystkie poza ,,placeholderami dla komponentów wykresów'', bo nie wiem, z jakiej technologii korzysta Tymek.

**Comment by Udiknedormin** [comment]
Zrobiona.
