### ISSUE TITLE
API Gateway: Przyjmuje host-id, monitor-id, zwraca hostId, monitorId

### ISSUE THREAD

**Issue by Udiknedormin** [mateusz59861/PZ-gr.2#36]
API Gateway przyjmuje, zgodnie z API na wiki, host-id, monitor-id itd. Zwraca jednak, tak samo jak Monitor, hostId, monitorId itd. O ile Monitor jest ,,szczegółem'', bo klient webowy i automatyczny z niego nie korzystają, o tyle API Gateway to publiczny interfejs, musi zgadzać się z dokumentacją.

**Comment by IgnacyMigas** [comment]
Nie jest to problem API Gateway, Monitor musi to naprawić. Gateway jest tylko pośrednikiem, dlatego uważam że nie powinien walidować odpowiedzi z Monitorów.
