### ISSUE TITLE
API Gateway: Nie umożliwia dostępu przeglądarkowego z tego samego serwera

### ISSUE THREAD

**Issue by Udiknedormin** [mateusz59861/PZ-gr.2#39]
W przypadku prób pobrania danych z tego samego serwera, zgłaszany jest błąd braku ustawionego Access-Control-Allow-Origin. Nieodtwarzalne w CURL-u i innych podobnych narzędziach, to specyficzna cecha przeglądarek.

**Comment by Udiknedormin** [comment]
Po wczorajszym patchu występuje nadal.

**Comment by IgnacyMigas** [comment]
Błąd u mnie zniknął i nie jestem w stanie go zreprodukować. Jeśli nadal występuję to proszę o kroki do reprodukcji.

**Comment by Udiknedormin** [comment]
API Gateway sam nie przyjmował nagłówka Access-Control-Allow-Origin, ale bez tegoż póki co wszystko chodzi, więc sprawa do zamkniecia. Najwyżej dam znać gdyby jednak był potrzebny.
