### ISSUE TITLE
API Gateway: Akceptuje monitory, które mogą uniemożliwić inne operacje

### ISSUE THREAD

**Issue by Udiknedormin** [mateusz59861/PZ-gr.2#46]
W przypadku dodania monitora o path-u, z którego nie da się pobrać danych, próba pobrania danych, np. metryk, rzuca wyjątek:

Exception Value:
No connection adapters were found for (PATH)
$HOME/.local/lib/python3.6/site-packages/requests/sessions.py in get_adapter, line 731

Spodziewane zachowanie: dodanie monitora, z którym nie da się połączyć nie powinno psuć działania innych. Optymalnie byłoby gdyby informacja o niepoprawnym połączeniu szła przy dodawaniu monitora (jakiś test połączenia?).

**Comment by IgnacyMigas** [comment]
Proszę podać kroki reprodukcji, ponieważ gateway powinien wykryć i usunąć błędny monitor.

**Comment by Udiknedormin** [comment]
Przy założeniu, że monitor jest pod url "127.0.0.1:8080", jeśli podany url to np. "127.0.0.1:8080/v1", Monitor wstępnie go akceptuje i dodaje. Następnie po wywołaniu "v1/metrics" zapytanie to kończy się rzuceniem opisanego wyjątku.

**Comment by IgnacyMigas** [comment]
Bug naprawiony
