### ISSUE TITLE
Monitor: Nie reaguje na "recursive: true" dla metrics i hosts

### ISSUE THREAD

**Issue by Udiknedormin** [mateusz59861/PZ-gr.2#47]
Inne headery prawdopodobnie analogicznie.

**Comment by 4papiez** [comment]
Przetestowane na:
http://localhost:8080/v1/metrics?recursive=true
http://localhost:8080/v1/metrics?recursive=false
http://localhost:8080/v1/metrics
http://localhost:8080/v1/hosts?recursive=true
http://localhost:8080/v1/hosts?recursive=false
http://localhost:8080/v1/hosts

Działa poprawnie.

**Comment by Udiknedormin** [comment]
Zgodnie z dokumentacją recursive to header, nie parametr zapytania. Czyli nie, nie działa poprawnie.

**Comment by Udiknedormin** [comment]
Wycofuję, źle spojrzałam, że to nie header tylko param.
