### ISSUE TITLE
API Gateway: obsługuje niepoprawnie odpowiedź od Authentication Service?

### ISSUE THREAD

**Issue by Udiknedormin** [mateusz59861/PZ-gr.2#62]
Kiedy token nie jest prawidłowy, Auth Service rzuca wyjątek... a API Gateway (albo Monitor, nie wnikam) rzuca kod 401 (powiedzmy, że ok) i jako odpowiedź HTTP podaje... kod HTML strony z błędem. Oczekiwane jest, żeby zamiast tego zwracał jakiś sensowny komunikat błędu (i kod, bo ,,nie znaleziono'' nie jest dobrym opisem na ,,błędna autentyfikacja'').

Zakładam, że skoro API Gateway rzuca na konsolę "Unauthorized: /v1/metrics" (czy analogi zależnie od URI) to tak w ogóle wychwytuje, że wystąpił błąd autentyfikacji.

**Comment by IgnacyMigas** [comment]
Nie udało mi się odtworzyć tego w API Gateway, to jest problem Auth Service który rzuca tym wyjątkiem (nie udało mi się, żeby ten komunikat przedostał się przez API Gateway)
