### ISSUE TITLE
APi Gateway: wysyła coś, co nie jest "application/json" do Auth Service?

### ISSUE THREAD

**Issue by Udiknedormin** [mateusz59861/PZ-gr.2#63]
Auth Service rzuca:
ERROR in app: Exception on /v1/protected [GET]
...
flask_jwt_extended.exceptions.NoAuthorizationError: Invalid content-type. Must be application/json

Oznacza to, że API Gateway wysyła do niego coś, co nie jest jsonem tylko, przypuszczalnie, stringiem.

**Comment by IgnacyMigas** [comment]
Poprawione

**Comment by Udiknedormin** [comment]
Proszę oddawać do review, a nie zamykać jeśli jest niespradzone (a powinno być). AuthService zwraca:

flask_jwt_extended.exceptions.NoAuthorizationError: Missing "access_token" key in json data.

**Comment by IgnacyMigas** [comment]
To nie jest zgłoszony błąd. 
"flask_jwt_extended.exceptions.NoAuthorizationError: Missing "access_token" key in json data."
Odnosi się do AuthService a nie do API Gateway, w szczególności do błędu:
flask_jwt_extended.exceptions.NoAuthorizationError: Invalid content-type. Must be application/json
który jest innym błędem.
Proszę wcześniej samemu sprawdzać czy opis błędu się zgadza z tym zgłoszonym.

**Comment by Udiknedormin** [comment]
1. Nie jestem debuggerem.

2. Proszę sprawdzać swoje commity integracji z innymi modułami in the first place.

> ten błąd odnosi się do AuthService
3. Commit API Gateway "params=body" -> "data=body", po którym błąd przestał występować sugeruje co innego.

> w szczególności do błędu: Must be application/json
4. Brak składowej 'data' sugeruje, że istotnie nie był przesyłany żaden json.

Proszę testować swój kod przed wrzucaniem go jako poprawny.

**Comment by Udiknedormin** [comment]
> ten błąd odnosi się do AuthService
Commit API Gateway "params=body" -> "data=body", po którym błąd przestał występować sugeruje co innego.

Proszę testować swój kod przed wrzucaniem go jako poprawny.
