### ISSUE TITLE
API Gateway: POST na /v1/metrics wywołuje błąd formatu danych

### ISSUE THREAD

**Issue by Udiknedormin** [mateusz59861/PZ-gr.2#77]
Nagłówki:
access_token: (stosowny, inaczej wywala 401, zgodnie z oczekiwaniami)
Content-Type: application/json

Ciało:
{  
   "kind": "CPU [%]",
   "metric-ids": "CM 2019-05-30 20:00:04.474",
   "monitor-id": "v1",
   "type": "moving-avg"
}

Odpowiedź:
415 (Unsupported Media Type)
{
  "timestamp": 1559586919331,
  "status": 415,
  "error": "Unsupported Media Type",
  "message": "Content type 'application/octet-stream' not supported",
  "path": "/v1/metrics"
}

**Comment by IgnacyMigas** [comment]
Problem został naprawiony. I taka mała poprawka, powinien być access-token zamiast access_token.
